package org.iceforge.skadi.sqlgateway.cache;

import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

class QueryCacheKeyTest {

    @Test
    void sameQuerySameUserProducesSameKey() {
        String k1 = QueryCacheKey.of("SELECT id FROM orders", "alice");
        String k2 = QueryCacheKey.of("SELECT id FROM orders", "alice");
        assertThat(k1).isEqualTo(k2);
    }

    @Test
    void whitespaceVariationProducesSameKey() {
        String k1 = QueryCacheKey.of("SELECT  id  FROM  orders", "alice");
        String k2 = QueryCacheKey.of("SELECT id FROM orders", "alice");
        assertThat(k1).isEqualTo(k2);
    }

    @Test
    void caseVariationProducesSameKey() {
        String k1 = QueryCacheKey.of("select id from orders", "alice");
        String k2 = QueryCacheKey.of("SELECT ID FROM ORDERS", "alice");
        assertThat(k1).isEqualTo(k2);
    }

    @Test
    void differentUsersProduceDifferentKeys() {
        String k1 = QueryCacheKey.of("SELECT id FROM orders", "alice");
        String k2 = QueryCacheKey.of("SELECT id FROM orders", "bob");
        assertThat(k1).isNotEqualTo(k2);
    }

    @Test
    void differentSqlProducesDifferentKeys() {
        String k1 = QueryCacheKey.of("SELECT id FROM orders", "alice");
        String k2 = QueryCacheKey.of("SELECT id FROM customers", "alice");
        assertThat(k1).isNotEqualTo(k2);
    }

    @Test
    void nullUserTreatedAsEmptyString() {
        String k1 = QueryCacheKey.of("SELECT 1", null);
        String k2 = QueryCacheKey.of("SELECT 1", "");
        assertThat(k1).isEqualTo(k2);
    }

    @Test
    void commentStrippedBeforeKey() {
        String k1 = QueryCacheKey.of("SELECT id FROM orders -- generated by Tableau", "alice");
        String k2 = QueryCacheKey.of("SELECT id FROM orders", "alice");
        assertThat(k1).isEqualTo(k2);
    }
}
