package org.iceforge.skadi.semantic;

import org.springframework.boot.context.properties.ConfigurationProperties;

/**
 * Configuration properties for the market-risk sensitivity plain-English demo spike
 * and the structured semantic JDBC demo endpoint.
 *
 * <pre>{@code
 * skadi:
 *   semantic:
 *     demo:
 *       enabled: false                                              # default; must opt-in
 *       default-limit: 500
 *       max-limit: 5000
 *       exposure-view: demo.market_risk.v_sensitivity_exposure_demo
 *       history-view:  demo.market_risk.v_sensitivity_history_demo
 *       # Structured JDBC demo endpoint (POST /api/semantic/v1/demo/query):
 *       execution-mode: disabled       # disabled | skadi_server_delegated | jdbc_direct
 *       datasource-id: default         # skadi.jdbc.datasources key to use for JDBC_DIRECT
 *       market-risk-view: demo.market_risk.v_market_risk_demo
 *       max-rows: 100                  # hard LIMIT appended to generated SQL
 *       query-timeout-ms: 30000        # JDBC query timeout; 0 = no timeout
 * }</pre>
 *
 * <p>Both endpoints are inactive when {@code enabled=false} (the default).
 * Set {@code enabled=true} explicitly to activate the demo spike endpoints.
 */
@ConfigurationProperties(prefix = "skadi.semantic.demo")
public class DemoSemanticProperties {

    /** Whether the demo endpoints are active. Defaults to {@code false}. */
    private boolean enabled = false;

    /** Default row limit applied to rendered SQL (plain-English demo). */
    private int defaultLimit = 500;

    /** Hard maximum cap applied to rendered SQL row limit (plain-English demo). */
    private int maxLimit = 5000;

    /** Fully-qualified view name for exposure-grid (GRID) queries. */
    private String exposureView = "demo.market_risk.v_sensitivity_exposure_demo";

    /** Fully-qualified view name for historical time-series (TIMESERIES) queries. */
    private String historyView = "demo.market_risk.v_sensitivity_history_demo";

    // ── Structured JDBC demo endpoint (POST /api/semantic/v1/demo/query) ───────

    /**
     * Execution mode for the structured demo endpoint.
     * Accepted values: {@code disabled}, {@code skadi_server_delegated}, {@code jdbc_direct}.
     */
    private String executionMode = "disabled";

    /** datasource-id key from {@code skadi.jdbc.datasources} used in JDBC_DIRECT mode. */
    private String datasourceId = "default";

    /** Fully-qualified view/table name used in SQL generated by the structured demo renderer. */
    private String marketRiskView = "demo.market_risk.v_market_risk_demo";

    /** Hard row cap appended as LIMIT in generated SQL. */
    private int maxRows = 100;

    /** JDBC query timeout in milliseconds; 0 means no timeout. */
    private int queryTimeoutMs = 30000;

    public boolean isEnabled()           { return enabled; }
    public void setEnabled(boolean v)    { this.enabled = v; }

    public int getDefaultLimit()         { return defaultLimit; }
    public void setDefaultLimit(int v)   { this.defaultLimit = v; }

    public int getMaxLimit()             { return maxLimit; }
    public void setMaxLimit(int v)       { this.maxLimit = v; }

    public String getExposureView()           { return exposureView; }
    public void   setExposureView(String v)   { this.exposureView = v; }

    public String getHistoryView()            { return historyView; }
    public void   setHistoryView(String v)    { this.historyView = v; }

    public String getExecutionMode()          { return executionMode; }
    public void   setExecutionMode(String v)  { this.executionMode = v; }

    public String getDatasourceId()           { return datasourceId; }
    public void   setDatasourceId(String v)   { this.datasourceId = v; }

    public String getMarketRiskView()         { return marketRiskView; }
    public void   setMarketRiskView(String v) { this.marketRiskView = v; }

    public int getMaxRows()                   { return maxRows; }
    public void setMaxRows(int v)             { this.maxRows = v; }

    public int getQueryTimeoutMs()            { return queryTimeoutMs; }
    public void setQueryTimeoutMs(int v)      { this.queryTimeoutMs = v; }
}
