package org.iceforge.skadi.sqlgateway.trace;

import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

class QueryFingerprintTest {

    @Test
    void sameSqlProducesSameFingerprint() {
        String a = QueryFingerprint.of("SELECT id FROM orders");
        String b = QueryFingerprint.of("SELECT id FROM orders");
        assertThat(a).isEqualTo(b);
    }

    @Test
    void whitespaceVariationProducesSameFingerprint() {
        String a = QueryFingerprint.of("SELECT  id  FROM  orders");
        String b = QueryFingerprint.of("SELECT id FROM orders");
        assertThat(a).isEqualTo(b);
    }

    @Test
    void caseVariationProducesSameFingerprint() {
        String a = QueryFingerprint.of("select id from orders");
        String b = QueryFingerprint.of("SELECT ID FROM ORDERS");
        assertThat(a).isEqualTo(b);
    }

    @Test
    void differentSqlProducesDifferentFingerprint() {
        String a = QueryFingerprint.of("SELECT id FROM orders");
        String b = QueryFingerprint.of("SELECT id FROM customers");
        assertThat(a).isNotEqualTo(b);
    }

    @Test
    void fingerprintIsEightHexChars() {
        String fp = QueryFingerprint.of("SELECT 1");
        assertThat(fp).hasSize(8).matches("[0-9a-f]{8}");
    }

    @Test
    void nullInputReturnsZeroFingerprint() {
        assertThat(QueryFingerprint.of(null)).isEqualTo("00000000");
    }

    @Test
    void blankInputReturnsZeroFingerprint() {
        assertThat(QueryFingerprint.of("   ")).isEqualTo("00000000");
    }

    @Test
    void commentStrippedBeforeFingerprint() {
        String a = QueryFingerprint.of("SELECT id FROM orders -- generated by Tableau");
        String b = QueryFingerprint.of("SELECT id FROM orders");
        assertThat(a).isEqualTo(b);
    }
}
